name: Test

description: Run clojure tests

inputs:
  template-lib-name:
    description: 'Name of the test to run'
    required: true

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v2  
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Run Tests
      shell: bash
      run: bb test:${{ inputs.template-lib-name }}
