name: Test

description: Run clojure tests

inputs:
  template-lib-name:
    description: 'Name of the test to run'
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        cli: 'latest'
        bb: 'latest'

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Run Tests
      shell: bash
      run: bb test:${{ inputs.template-lib-name }}
