name: Dalfox

description: Starts the Clojure server and runs tests.

inputs:
  template-lib-name:
    description: "Name of the test to run"
    required: true

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v2
    - name: Install Dalfox
      shell: bash
      run: sudo snap install dalfox

    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - name: Start server
      shell: bash
      run: nohup bb server &

    - name: Wait for server to start
      shell: bash
      run: bb wait

    - name: Run Tests
      shell: bash
      run: bb dalfox:${{ inputs.template-lib-name }}
