name: Selmer clojure tests

on: [push]

jobs:
  test-selmer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clojure tests
        uses: ./.github/actions/clojure-test
        with:
          template-lib-name: selmer
