name: Hiccup clojure tests

on: [push]

jobs:
  test-hiccup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Clojure tests
        uses: ./.github/actions/clojure-test
        with:
          template-lib-name: hiccup
