name: Hiccup Tests

on: [push]

jobs:
  test-hiccup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test with dalfox
        uses: ./.github/actions/dalfox
        with:
          template-lib-name: hiccup
      - name: Clojure tests
        uses: ./.github/actions/clojure-test
        with:
          template-lib-name: hiccup
