name: Hiccup Tests

on: [push]

jobs:
  test-hiccup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run Start Server Action
        uses: ./.github/actions/dalfox
        with:
          template-lib-name: hiccup
